name       : fd
version    : 7.0.0
release    : 1
source     :
    - https://github.com/sharkdp/fd/archive/v7.0.0.tar.gz : 93cc5a7c9199dc650f51a491e4ed4512262eeaeae5847722e6886763b41e2896
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find.
description: |
    fd is a simple, fast and user-friendly alternative to the find command.

    While it does not seek to mirror all of find's powerful functionality, it provides
    sensible (opinionated) defaults for 80% of the use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install
    install -Dm00755 ~/.cargo/bin/fd $installdir/usr/bin/fd
    install -Dm00755 doc/fd.1 /$installdir/usr/share/man/man1/fd.1
check      : |
    cargo test

