name       : fd
version    : 8.5.2
release    : 15
source     :
    - https://github.com/sharkdp/fd/archive/refs/tags/v8.5.2.tar.gz : bc66842481d2121f58e7b178b449b5d387078fabcf712355e8db10f9a7af2cd7
homepage   : https://github.com/sharkdp/fd
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find
description: |
    fd is a program to find entries in your filesystem. It is a simple, fast and user-friendly alternative to find. While it does not aim to support all of find's powerful functionality, it provides sensible (opinionated) defaults for a majority of use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
    %make completions
install    : |
    install -Dm00755 target/release/fd $installdir/usr/bin/fd
    install -Dm00644 doc/fd.1 $installdir/usr/share/man/man1/fd.1
    install -Dm00644 autocomplete/fd.bash $installdir/usr/share/bash-completion/completions/fd
    install -Dm00644 autocomplete/fd.fish $installdir/usr/share/fish/vendor_completions.d/fd.fish
    install -Dm00644 autocomplete/_fd $installdir/usr/share/zsh/site-functions/_fd
check      : |
    cargo test --all
