name       : fd
version    : 7.3.0
release    : 4
source     :
    - https://github.com/sharkdp/fd/archive/v7.3.0.tar.gz : fbd48cc83c90a0ab09fc3bbe865708a3a528876a99f8304a17d07af7fb378170
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find.
description: |
    fd is a simple, fast and user-friendly alternative to the find command.

    While it does not seek to mirror all of find's powerful functionality, it provides
    sensible (opinionated) defaults for 80% of the use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path .
    install -Dm00755 ~/.cargo/bin/fd $installdir/usr/bin/fd
    install -Dm00755 doc/fd.1 /$installdir/usr/share/man/man1/fd.1
check      : |
    cargo test

