name       : fd
version    : 8.2.1
release    : 9
source     :
    - https://github.com/sharkdp/fd/archive/v8.2.1.tar.gz : 429de7f04a41c5ee6579e07a251c72342cd9cf5b11e6355e861bb3fffa794157
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find.
description: |
    fd is a simple, fast and user-friendly alternative to the find command.

    While it does not seek to mirror all of find's powerful functionality, it provides sensible (opinionated) defaults for 80% of the use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/fd $installdir/usr/bin/fd
    install -Dm00644 doc/fd.1 $installdir/usr/share/man/man1/fd.1
    install -Dm00644 target/release/build/fd-*/out/fd.bash $installdir/usr/share/bash-completion/completions/fd
    install -Dm00644 target/release/build/fd-*/out/fd.fish $installdir/usr/share/fish/vendor_completions.d/fd.fish
    install -Dm00644 contrib/completion/_fd $installdir/usr/share/zsh/site-functions/_fd
check      : |
    cargo test --all
