name       : fd
version    : 8.1.1
release    : 8
source     :
    - https://github.com/sharkdp/fd/archive/v8.1.1.tar.gz : 7b327dc4c2090b34c7fb3e5ac7147f7bbe6266c2d44b182038d36f3b1d347cc1
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find.
description: |
    fd is a simple, fast and user-friendly alternative to the find command.

    While it does not seek to mirror all of find's powerful functionality, it provides sensible (opinionated) defaults for 80% of the use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/fd $installdir/usr/bin/fd
    install -Dm00644 doc/fd.1 $installdir/usr/share/man/man1/fd.1
    install -Dm00644 target/release/build/fd-*/out/fd.bash $installdir/usr/share/bash-completion/completions/fd
    install -Dm00644 target/release/build/fd-*/out/_fd $installdir/usr/share/zsh/site-functions/_fd
    install -Dm00644 target/release/build/fd-*/out/fd.fish $installdir/usr/share/fish/vendor_completions.d/fd.fish
check      : |
    cargo test --all
