name       : fd
version    : 7.1.0
release    : 2
source     :
    - https://github.com/sharkdp/fd/archive/v7.1.0.tar.gz : 9385a55738947f69fd165781598de6c980398c6214a4927fce13a4f7f1e63d4d
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find.
description: |
    fd is a simple, fast and user-friendly alternative to the find command.

    While it does not seek to mirror all of find's powerful functionality, it provides
    sensible (opinionated) defaults for 80% of the use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install
    install -Dm00755 ~/.cargo/bin/fd $installdir/usr/bin/fd
    install -Dm00755 doc/fd.1 /$installdir/usr/share/man/man1/fd.1
check      : |
    cargo test

