name       : fd
version    : 8.4.0
release    : 14
source     :
    - https://github.com/sharkdp/fd/archive/refs/tags/v8.4.0.tar.gz : d0c2fc7ddbe74e3fd88bf5bb02e0f69078ee6d2aeea3d8df42f508543c9db05d
homepage   : https://github.com/sharkdp/fd
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find
description: |
    fd is a program to find entries in your filesystem. It is a simple, fast and user-friendly alternative to find. While it does not aim to support all of find's powerful functionality, it provides sensible (opinionated) defaults for a majority of use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/fd $installdir/usr/bin/fd
    install -Dm00644 doc/fd.1 $installdir/usr/share/man/man1/fd.1
    install -Dm00644 target/release/build/fd-*/out/fd.bash $installdir/usr/share/bash-completion/completions/fd
    install -Dm00644 target/release/build/fd-*/out/fd.fish $installdir/usr/share/fish/vendor_completions.d/fd.fish
    install -Dm00644 contrib/completion/_fd $installdir/usr/share/zsh/site-functions/_fd
check      : |
    cargo test --all
