name       : fd
version    : 8.0.0
release    : 6
source     :
    - https://github.com/sharkdp/fd/archive/v8.0.0.tar.gz : fba93204c10266317e0981914c630b08e12cd322c75ff2a2e504ff1dce17d557
license    :
    - Apache-2.0
    - MIT
component  : system.utils
networking : yes
summary    : A simple, fast and user-friendly alternative to find.
description: |
    fd is a simple, fast and user-friendly alternative to the find command.

    While it does not seek to mirror all of find's powerful functionality, it provides
    sensible (opinionated) defaults for 80% of the use cases.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path .
    install -Dm00755 ~/.cargo/bin/fd $installdir/usr/bin/fd
    install -Dm00755 doc/fd.1 /$installdir/usr/share/man/man1/fd.1
check      : |
    cargo test
